"""
knowledge_base.py
Design knowledge seeded into the FAISS vector store.
Covers all 6 agent domains: visual, ux, accessibility, market, design_system, competitor.
HuggingFace-style: each doc has content + metadata for filtered retrieval.
"""

DESIGN_KNOWLEDGE = [
    # ── VISUAL ───────────────────────────────────────────────────────────────
    {"content": "Visual hierarchy uses size, contrast, color, and spacing to direct attention. Primary elements should be 2x the visual weight of secondary elements. The eye follows size → color → position in that order.", "category": "visual", "source": "Visual Design Principles", "severity": "critical"},
    {"content": "60-30-10 color rule: 60% dominant (backgrounds/surfaces), 30% secondary (UI chrome), 10% accent (CTAs, highlights). Violating this creates visual noise. Brand colors should live in the 10% accent band.", "category": "visual", "source": "Color Theory", "severity": "warning"},
    {"content": "Typography: limit to 2 typefaces, 3 weights max. Modular type scale 1.25x or 1.333x. Body text 16px minimum, line-height 1.5–1.6x. Heading contrast with body must be at least 2 size steps.", "category": "visual", "source": "Typography Standards", "severity": "warning"},
    {"content": "8px base grid system is industry standard. All spacing values should be multiples of 8 (8, 16, 24, 32, 40, 48, 64). Component padding: 16px internal, 24px between components, 48px+ section gaps.", "category": "visual", "source": "Grid Systems", "severity": "good"},
    {"content": "Button hierarchy: Primary (filled brand color) > Secondary (outlined) > Tertiary (ghost/text). Never two primary buttons adjacent. Minimum button height 36px desktop, 44px mobile. Padding 16px horizontal.", "category": "visual", "source": "Component Design", "severity": "critical"},
    {"content": "Card design: consistent border-radius (4px, 8px, 12px — pick one), 1px border or subtle shadow, internal padding 16–24px. Cards at the same hierarchy level must be visually identical.", "category": "visual", "source": "Card Patterns", "severity": "warning"},
    {"content": "Whitespace is a design element. Crowded interfaces increase cognitive load. Use generous margins: 64px+ page margins desktop, 24px mobile. Section spacing 80–120px on landing pages.", "category": "visual", "source": "Layout Principles", "severity": "warning"},
    {"content": "Icon consistency: never mix filled and outlined icons in same UI. Size 16px inline, 24px UI controls, 32px+ decorative. All icons from same family (Material, Phosphor, Heroicons, etc).", "category": "visual", "source": "Iconography", "severity": "warning"},

    # ── UX ────────────────────────────────────────────────────────────────────
    {"content": "Nielsen's 10 Heuristics: visibility of status, real-world match, user control/freedom, consistency/standards, error prevention, recognition over recall, flexibility/efficiency, minimal design, error recovery, help/docs.", "category": "ux", "source": "Nielsen Norman Group", "severity": "critical"},
    {"content": "CTA best practices: action verbs (Get, Start, Try, Download), under 4 words, above fold for primary action, contrast ratio ≥ 4.5:1 against background, visual affordance (border-radius, elevation).", "category": "ux", "source": "Conversion Optimization", "severity": "critical"},
    {"content": "F-pattern scanning on text-heavy pages, Z-pattern on visual pages. Place key content in first two horizontal sweeps and down the left spine. Navigation items read left to right by priority.", "category": "ux", "source": "Eye Tracking Research", "severity": "warning"},
    {"content": "Cognitive load: chunk info into groups of 5–9 (Miller's Law). Progressive disclosure: show only what's needed per step. One primary action per screen. Avoid jargon — plain language always wins.", "category": "ux", "source": "Cognitive Psychology", "severity": "critical"},
    {"content": "Fitts's Law: target acquisition time = distance / size. Make primary actions large (44px+ height) and close to natural resting positions. Mobile: bottom third of screen for thumb reach zone.", "category": "ux", "source": "Interaction Design", "severity": "critical"},
    {"content": "Form UX: label above field (not placeholder-only). Inline validation on blur. Single-column layout for linear flows. Mark required fields consistently. Error messages specific + actionable.", "category": "ux", "source": "Form Design Research", "severity": "warning"},
    {"content": "Navigation: 5–7 items max in primary nav. Descriptive labels not clever ones. Active state clearly visible. Breadcrumbs for 3+ level hierarchies. Mobile hamburger only as last resort.", "category": "ux", "source": "Information Architecture", "severity": "warning"},
    {"content": "Loading states: show skeleton screens (not spinners) for content >300ms. Progress bars for operations >1s. Never leave users wondering if an action registered — immediate visual feedback.", "category": "ux", "source": "Feedback Patterns", "severity": "warning"},
    {"content": "Empty states are opportunities: explain what's missing + provide a clear next action. Never show a blank screen. Illustration + action button + 1-line explanation is the gold standard.", "category": "ux", "source": "Empty State Design", "severity": "good"},

    # ── ACCESSIBILITY ─────────────────────────────────────────────────────────
    {"content": "WCAG 2.1 AA: normal text (<18pt) contrast ≥ 4.5:1. Large text (≥18pt or 14pt bold) ≥ 3:1. UI components and graphics ≥ 3:1. AAA requires 7:1 for normal text. Test with real contrast checkers.", "category": "accessibility", "source": "WCAG 2.1 SC 1.4.3", "severity": "critical"},
    {"content": "Keyboard accessibility: all interactive elements Tab-reachable. Logical order left-to-right top-to-bottom. Visible focus indicators (2px outline, 3:1 contrast against surroundings). No keyboard traps.", "category": "accessibility", "source": "WCAG 2.1 SC 2.1", "severity": "critical"},
    {"content": "Images: descriptive alt text for informative images (WCAG 1.1.1). Decorative images: alt=''. Complex images (charts, diagrams): extended description in text. Never communicate via color alone.", "category": "accessibility", "source": "WCAG 2.1 SC 1.1.1", "severity": "critical"},
    {"content": "Touch targets: minimum 44x44 CSS pixels (Apple HIG), 48x48dp (Material Design). Spacing between targets ≥ 8px to prevent mis-taps. WCAG 2.5.5 Target Size is Level AAA at 44px.", "category": "accessibility", "source": "WCAG 2.5.5 / Platform HIG", "severity": "warning"},
    {"content": "Text resize: UI must work at 200% zoom (WCAG 1.4.4). Avoid fixed heights on text containers. Use rem/em units. Horizontal scroll should not be required at 320px width.", "category": "accessibility", "source": "WCAG 2.1 SC 1.4.4", "severity": "warning"},
    {"content": "Semantic HTML: heading hierarchy h1→h2→h3 no skipping. ARIA roles for custom components. Form inputs with explicit <label>. Landmark regions: header, main, nav, footer for screen reader navigation.", "category": "accessibility", "source": "WCAG 2.1 SC 1.3.1", "severity": "critical"},
    {"content": "Animation: pause/stop/hide control for auto-playing content >5s (WCAG 2.2.2). Respect prefers-reduced-motion. No flashing >3 times/second (seizure risk, WCAG 2.3.1).", "category": "accessibility", "source": "WCAG 2.1 SC 2.2.2", "severity": "warning"},

    # ── MARKET / COMPETITIVE ──────────────────────────────────────────────────
    {"content": "SaaS dashboard 2024 conventions: left collapsible sidebar, top bar with search + user menu, card KPIs, data tables with bulk actions, dark mode toggle. Deviation increases onboarding friction.", "category": "market", "source": "SaaS Design Patterns 2024", "severity": "warning"},
    {"content": "Mobile-first 2024: 63% of web traffic is mobile. Design for 375px viewport minimum. Bottom navigation for mobile apps. Thumb zone: bottom 40% of screen is primary interaction area.", "category": "market", "source": "Mobile UX 2024", "severity": "critical"},
    {"content": "Landing page conversion: single headline value prop, supporting sub-headline, social proof in first viewport (logos/numbers/testimonials), CTA every 2–3 sections. Video above fold converts 80% better.", "category": "market", "source": "CRO Research 2024", "severity": "warning"},
    {"content": "E-commerce: product images 3+ angles + zoom. Price prominent + anchoring (crossed-out original). Add-to-cart above fold. Reviews/ratings near price. Trust signals (returns, security) visible.", "category": "market", "source": "E-commerce UX 2024", "severity": "critical"},
    {"content": "Design maturity signals: consistent spacing system, documented tokens, component library, responsive breakpoints, motion guidelines. Ad-hoc designs show mismatched spacing, mixed radius values, inconsistent color use.", "category": "market", "source": "Design System Benchmarks", "severity": "good"},

    # ── DESIGN SYSTEM ─────────────────────────────────────────────────────────
    {"content": "Design tokens: separate primitive tokens (color-blue-500) from semantic tokens (color-interactive-primary). Semantic tokens reference primitives. This enables theming without touching component code.", "category": "design_system", "source": "Design Token Standards", "severity": "critical"},
    {"content": "Component audit checklist: consistent naming convention, documented props/variants, responsive behavior defined, dark mode tested, accessibility annotations present, motion/animation specs.", "category": "design_system", "source": "Component Audit Framework", "severity": "warning"},
    {"content": "Spacing tokens: use a fixed scale (4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96px). Ad-hoc spacing (17px, 23px) signals absence of a system. All padding/margin/gap values should be on the scale.", "category": "design_system", "source": "Spacing Systems", "severity": "warning"},
    {"content": "Color system: 9-10 step scales per color (50–900). Semantic layer: surface, background, border, text, interactive, status (success/warning/error/info). Each with default, hover, pressed, disabled states.", "category": "design_system", "source": "Color System Design", "severity": "warning"},
    {"content": "Typography system: define type roles (display, heading, body, caption, code). Each role has size, weight, line-height, letter-spacing defined. Never use arbitrary font sizes outside the type scale.", "category": "design_system", "source": "Type Systems", "severity": "warning"},

    # ── COMPETITOR / IMAGE RAG ────────────────────────────────────────────────
    {"content": "Dribbble top UI patterns 2024: glassmorphism fading, bento grid layouts rising, variable fonts for hierarchy, 3D illustration accents, dark mode as default, micro-animations on interaction.", "category": "competitor", "source": "Dribbble Trends 2024", "severity": "good"},
    {"content": "Mobbin benchmark: top apps use bottom tab navigation (5 items max), card-based feeds, persistent search, gesture-based navigation. Onboarding: 3-4 screens max, value-first not feature-first.", "category": "competitor", "source": "Mobbin App Analysis 2024", "severity": "good"},
    {"content": "SaaS competitive positioning: differentiation through UX (not just features) is the top growth lever in 2024. Products with design systems ship 30% faster. Accessibility compliance is now table stakes.", "category": "competitor", "source": "SaaS UX Benchmarks 2024", "severity": "good"},
    {"content": "Image similarity analysis: compare uploaded design against reference library using embedding similarity. Scores >0.85 indicate close similarity to reference pattern. Use for detecting design convention adherence.", "category": "competitor", "source": "Image RAG Methodology", "severity": "good"},
]
